# Generated by Django 3.2.3 on 2021-06-02 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import taskManager.enumTasks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('finish', models.DateTimeField(null=True)),
                ('priority', enumfields.fields.EnumField(enum=taskManager.enumTasks.Priority, max_length=10)),
                ('status', enumfields.fields.EnumField(enum=taskManager.enumTasks.Status, max_length=10)),
                ('information', models.TextField(verbose_name='Information')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
